apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: community-graphql
secretGenerator:
- name: community-graphql-secrets
  envs:
  - .env

resources:
  - deployment.yaml
  - service.yaml