apiVersion: v1
kind: Service
metadata:
  labels:
     name: community-graphql
  name: community-graphql
spec:
  type: LoadBalancer
  selector:
    app: community-graphql
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
